[build-system]
requires = ["scikit-build-core >=0.4.3"]
build-backend = "scikit_build_core.build"

[project]
name = "kali"
version = "0.0.1"
description = "Realtime Rendering Research Framework"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Simon Kallweit", email = "simon.kallweit@gmail.com" }]
classifiers = ["License :: MIT"]

[project.urls]
Homepage = "https://github.com/westlicht/kali"

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.4"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"

cmake.args = ["--preset", "macos-clang", "-DCMAKE_DEFAULT_BUILD_TYPE=Release"]
